run:
  concurrency: 4
  timeout: 5m
  linters:
    enable:
      - deadcode
      - errcheck
      - gosimple
      - govet
      - ineffassign
      - staticcheck
      - structcheck
      - unused
      - varcheck
      - goimports
      - typecheck
      - gofmt
      - misspell
      - nestif
      - sqlclosecheck
      - gosec
